project:
  type: website
  output-dir: docs

website:
  title: "Industrial Proximity & the Cost of Nearby"
  navbar:
    left:
      - href: report/index.qmd
        text: Report

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    embed-resources: false